{"name": "get请求查询用户数据列表", "status": "failed", "statusDetails": {"message": "AssertionError: 第1个断言失败 -|- 实际结果:{'msg': 'pagenum 参数错误', 'status': 400} || 预期结果: {'msg': '登录成功', 'status': 200}", "trace": "cls = <class 'tools.data_process.DataProcess'>, response = {'data': None, 'meta': {'msg': 'pagenum 参数错误', 'status': 400}}\nexpect_str = '{\"$.meta\":{\\'msg\\': \\'登录成功\\', \\'status\\': 200}}'\n\n    @classmethod\n    def assert_result(cls, response: dict, expect_str: str):\n        \"\"\" 预期结果实际结果断言方法\n        :param response: 实际响应结果\n        :param expect_str: 预期响应内容，从excel中读取\n        return None\n        \"\"\"\n        # 后置sql变量转换\n        allure_step(\"当前可用参数池\", cls.extra_pool)\n        expect_str = rep_expr(expect_str, cls.extra_pool)\n        expect_dict = convert_json(expect_str)\n        index = 0\n        for k, v in expect_dict.items():\n            # 获取需要断言的实际结果部分\n            actual = extractor(response, k)\n            index += 1\n            logger.info(\n                f'第{index}个断言,实际结果:{actual} | 预期结果:{v} \\n断言结果 {actual == v}')\n            allure_step(f'第{index}个断言', f'实际结果:{actual} = 预期结果:{v}')\n            try:\n>               assert actual == v\nE               AssertionError\n\ntools/data_process.py:133: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\ncases = ['c4', 'get请求查询用户数据列表', '', 'users', 'get', 'data', ...]\n\n    def test_main(cases):   # 不使用数据库功能\n        # 发送请求\n        response, expect, sql = client.action(cases)\n        # 断言操作\n>       DataProcess.assert_result(response, expect)\n\ntest/test_api.py:35: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ncls = <class 'tools.data_process.DataProcess'>, response = {'data': None, 'meta': {'msg': 'pagenum 参数错误', 'status': 400}}\nexpect_str = '{\"$.meta\":{\\'msg\\': \\'登录成功\\', \\'status\\': 200}}'\n\n    @classmethod\n    def assert_result(cls, response: dict, expect_str: str):\n        \"\"\" 预期结果实际结果断言方法\n        :param response: 实际响应结果\n        :param expect_str: 预期响应内容，从excel中读取\n        return None\n        \"\"\"\n        # 后置sql变量转换\n        allure_step(\"当前可用参数池\", cls.extra_pool)\n        expect_str = rep_expr(expect_str, cls.extra_pool)\n        expect_dict = convert_json(expect_str)\n        index = 0\n        for k, v in expect_dict.items():\n            # 获取需要断言的实际结果部分\n            actual = extractor(response, k)\n            index += 1\n            logger.info(\n                f'第{index}个断言,实际结果:{actual} | 预期结果:{v} \\n断言结果 {actual == v}')\n            allure_step(f'第{index}个断言', f'实际结果:{actual} = 预期结果:{v}')\n            try:\n                assert actual == v\n            except AssertionError:\n>               raise AssertionError(\n                    f'第{index}个断言失败 -|- 实际结果:{actual} || 预期结果: {v}')\nE               AssertionError: 第1个断言失败 -|- 实际结果:{'msg': 'pagenum 参数错误', 'status': 400} || 预期结果: {'msg': '登录成功', 'status': 200}\n\ntools/data_process.py:135: AssertionError"}, "steps": [{"name": "请求地址: http://127.0.0.1:8000/api/private/v1/users", "status": "passed", "start": 1640847468138, "stop": 1640847468138}, {"name": "请求头", "status": "passed", "attachments": [{"name": "请求头", "source": "a023f5cf-3e6c-498c-8233-4fc4dbfa24b2-attachment.json", "type": "application/json"}], "start": 1640847468138, "stop": 1640847468139}, {"name": "请求数据", "status": "passed", "attachments": [{"name": "请求数据", "source": "5501481f-0782-4d62-84eb-6266c0d6f167-attachment.json", "type": "application/json"}], "start": 1640847468139, "stop": 1640847468139}, {"name": "响应耗时(s): 0.001626", "status": "passed", "start": 1640847468142, "stop": 1640847468142}, {"name": "响应结果", "status": "passed", "attachments": [{"name": "响应结果", "source": "8f544ef9-8e7b-445b-991a-ecfc578d6a26-attachment.json", "type": "application/json"}], "start": 1640847468142, "stop": 1640847468142}, {"name": "当前可用参数池", "status": "passed", "attachments": [{"name": "当前可用参数池", "source": "ca6a7873-2c8c-4403-bf98-cf9272b392a0-attachment.json", "type": "application/json"}], "start": 1640847468142, "stop": 1640847468142}, {"name": "第1个断言", "status": "passed", "attachments": [{"name": "第1个断言", "source": "7a35ea5a-6627-4208-87f7-fc945ec2b472-attachment.json", "type": "application/json"}], "start": 1640847468143, "stop": 1640847468143}], "parameters": [{"name": "cases", "value": "['c4', 'get请求查询用户数据列表', '', 'users', 'get', 'data', '', '{\"pagenum\": 1, \"pagesize\": \"12\"}', '', '', '{\"$.meta\":${meta}}']"}], "start": 1640847468138, "stop": 1640847468143, "uuid": "f82a72f2-60ba-4061-a32f-8c09aa7ae469", "historyId": "f9a3a528aa08d345b131e068670a2332", "testCaseId": "881516e7ef2e2aa5436f6a3c3e6a5bcb", "fullName": "test.test_api#test_main", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_api"}, {"name": "host", "value": "DXPdeMacBook-Pro.local"}, {"name": "thread", "value": "13075-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_api"}]}